export const API_REQUEST = 'API_REQUEST';
export const API_RECIEVE_SUCCESS = 'API_RECIEVE_SUCCESS';
export const API_RECIVE_FAILURE = 'API_RECIEVE_FAILURE';
export const FILTER_BY_PLANET_TEXT = 'FILTER_BY_PLANET_TEXT';
