const REQUEST_PLANETS_INFORMATION = 'REQUEST_PLANETS_INFORMATION';

const PLANET_INFO_REQUEST_SUCESS = 'PLANET_INFO_REQUEST_SUCESS';

const PLANET_INFO_REQUEST_FAILURE = 'PLANET_INFO_REQUEST_FAILURE';

export {
  REQUEST_PLANETS_INFORMATION,
  PLANET_INFO_REQUEST_SUCESS,
  PLANET_INFO_REQUEST_FAILURE,
};
