const REQUEST_PLANETS_INFORMATION = 'REQUEST_PLANETS_INFORMATION';

const PLANET_INFO_REQUEST_SUCESS = 'PLANET_INFO_REQUEST_SUCESS';

const PLANET_INFO_REQUEST_FAILURE = 'PLANET_INFO_REQUEST_FAILURE';

const FILTER_BY_NAME = 'FILTER_BY_NAME';

const FILTER_BY_NUMERIC_VALUES = 'FILTER_BY_NUMERIC_VALUES';

export {
  REQUEST_PLANETS_INFORMATION,
  PLANET_INFO_REQUEST_SUCESS,
  PLANET_INFO_REQUEST_FAILURE,
  FILTER_BY_NAME,
  FILTER_BY_NUMERIC_VALUES,
};
