export const API_REQUEST = 'API_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const INPUT_NAME = 'INPUT_NAME';
export const FILTER_BY_NUMERIC_VALUES = 'FILTER_BY_NUMERIC_VALUES';
